### ISSUE TITLE
When submitting to TestFlight, rejection due to FBSDKCoreKit beta

### ISSUE THREAD

**Issue by natanrolnik** [ParsePlatform/ParseFacebookUtils-iOS#34]
I just tried to submit my app to TestFlight, using:
- CocoaPods
- `use_frameworks!`
- ParseFacebookUtilsV4

I got the following error:

```
This bundle is invalid. The value for key CFBundleShortVersionString '4.9.0-beta2' in the Info.plist file must be a period-separated list of at most three non-negative integers.
```

Although the Info.plist of the app itself doesn't have any mention of the `4.9.0-beta2`, it seems that iTunes Connect somehow checks for Info.Plist files in the frameworks.

Any suggestions to what can be done in this case, besides downgrading to the previous ParseFacebookUtils?

I managed to do a workaround using a `post_install` hook on my `Podfile`, but this is far from ideal.

**Comment by nlutsenko** [comment]
Hey @natanrolnik, this sounds about right...
This was reported in https://github.com/CocoaPods/CocoaPods/issues/4437 and fixed in https://github.com/CocoaPods/CocoaPods/issues/4444

Since next version of CocoaPods is not yet out with these fixes - the only workaround that comes to my mind is to use `master` of CocoaPods gem in your workflow.

**Comment by natanrolnik** [comment]
Sounds good, @nlutsenko. Thanks!
