### ISSUE TITLE
appdelegate can't import PFFacebookUtils.h

### ISSUE THREAD

**Issue by makthrow** [ParsePlatform/ParseFacebookUtils-iOS#41]
Bridging Header File:
#import < ParseFacebookUtilsV4/PFFacebookUtils.h >

AppDelegate Error: Use of unresolved identifier PFFaceBookUtils
http://imgur.com/a/bojd6

If I add
import ParseFacebookUtilsV4 at the top  of the appdelegate file, everything works.

any advice for solving this appreciated.

**Comment by nlutsenko** [comment]
Hey @makthrow, are you using CocoaPods or some other kind of deployment?
You don't really need to use a bridging header in case of CocoaPods + frameworks, or with any of the downloadable frameworks from parse.com or GitHub releases page.

The intended flow is adding `import ParseFacebookUtilsV4` in your source files, since this is the flow for native Swift frameworks or the frameworks that Apple bundles with the OS.

**Comment by makthrow** [comment]
I am using Cocoapods.. yes. Ok, because some tutorials from 6 months ago I was following had me make a bridging header. So your'e saying I don't need that at all now? just add import to the top of my files..

**Comment by nlutsenko** [comment]
Yup, you don't need a bridging header at all, as long as you are using latest ParseFacebookUtilsV4, Parse and Facebook SDKs.
