### ISSUE TITLE
ParseFacebookUtilsV4 updates FBSDKCoreKit & FBSDKLoginKit to 4.9.0-beta2

### ISSUE THREAD

**Issue by acegreen** [ParsePlatform/ParseFacebookUtils-iOS#44]
Archiving error:
<img width="513" alt="screen shot 2016-01-12 at 10 49 59 pm" src="https://cloud.githubusercontent.com/assets/10794609/12284603/eb8e5f2a-b97e-11e5-8b72-68825cc2b285.png">

**Comment by nlutsenko** [comment]
Hey @acegreen, that sounds about right...

Are you installing via CocoaPods? Or some other way?
CocoaPods has a bug open for ages about this (should be fixed in 1.0.0-beta2).
If you are - please update it using something like `gem install cocoapods --pre`.

Apple enforces this restriction on bundles that you ship inside your app pretty recently.

**Comment by acegreen** [comment]
I updated to 1.0.0-beta2 a few days ago and had to revert. It was de-seomthing all my pods

**Comment by nlutsenko** [comment]
We are using FBSDK `4.9.0-beta2` for quite a while now (since ParseFacebookUtils `1.10.0`, which was about a month ago). 

You can also workaround this problem by changing the `CFBundleShortVersionString` inside the Info.plist of FBSDKCoreKit/FBSDKLoginKit to `4.9.0`, which should resolve this as well.
After install hook in your `Podfile` might help this as well, though it might be more effort, since official launch of FBSDK `4.9.0` is coming soon.

**Comment by acegreen** [comment]
Yea thats what I did, changed it to 4.9.0 until its out of beta.

**Comment by nlutsenko** [comment]
Glad you got it covered, thanks for reporting this though, as it definitely helps to know about these problems. Going to close out this issue, as it's not quite actionable from ParseFacebookUtilsV4 end.

**Comment by mitchellporter** [comment]
Experiencing the same thing.. I simply removed `-beta2` from the string.
