### ISSUE TITLE
Facebook SDK out of beta

### ISSUE THREAD

**Issue by bradfol** [ParsePlatform/ParseFacebookUtils-iOS#47]
It appears the dependency on the Facebook SDK no longer requires a beta version. Facebook SDK [4.9.1 was released January 16 with support for tvOS](https://developers.facebook.com/docs/ios/change-log-4.x).

Would be great to have an updated pod spec to rely on the new version. Thanks!

**Comment by bradfol** [comment]
Would also clear up some issues such as #44, #34, and #33.

**Comment by nlutsenko** [comment]
@bradfol, since the latest version is `4.9.1` - it will override the required dependency for `4.9.0-beta2` no problem. I've just tested this locally and got the following output:
```
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.6.0)
Installing FBSDKCoreKit (4.9.1)
Installing FBSDKLoginKit (4.9.1)
Installing Parse (1.12.0)
Installing ParseFacebookUtilsV4 (1.11.0)
Installing ParseUI (1.2.0)
```

for a Podfile with just:
```
use_frameworks!

pod 'Parse'
pod 'ParseFacebookUtilsV4'
pod 'ParseUI'
```

We will definetly update the requirement to 4.9.1, but I don't think there is a need for a release of the version of podspec right now.

**Comment by bradfol** [comment]
@nlutsenko Thanks!
